version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: registry.lgypro.com/dev/frontend:v1
    ports:
    - "3000:3000"
    volumes:
    - "/app/node_modules"
    - ".:/app"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
    - npm
    - run
    - test
    # stdin_open: true
    volumes:
    - "/app/node_modules"
    - ".:/app"